/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shiba' at '2/10/15 11:16 AM' with Gradle 2.2.1
 *
 * @author shiba, @date 2/10/15 11:16 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
